
# Localization strings
class Strings:
	def __init__(self, lang="hr"):
		if lang == "en":
			self.Help = "-lang en/hr/de\t\tForce language (currently supported: en, hr, de; default: hr)\n-debug\t\t\tEnable debug in EDAP module\n-alltests\t\tShow all tests instead of just from current date\n-loglevel 0/1/2/3\tSet log level (verbose/info/warning/error)\n-noanonrep\t\tDon't send anonymous error reports\n-fullavg\t\tShow only average of all subjects\n-nohidepriv\t\tDon't hide private info in debug logs\n-report\t\t\tStore a grade report into \"report.txt\"\n"
			self.CredentialPrompt = "Please enter your credentials.\nDISCLAIMER: Your credentials are sent only to \"ocjene.skole.hr\"\nand are kept in memory only for the duration of the login process.\n"
			self.UsernamePrompt = "Username: "
			self.PasswordPrompt = "Password: "
			self.ClassSelDisplay = "ID %s\n  Class: %s\n  Year: %s\n  School: %s\n  City: %s\n  Classmaster: %s"
			self.SelectionTemplate = "\nSelection (0 to %s): "
			self.ConcludedGradeMinified = "CONCLUDED"
			self.AverageGradeMinified = "AVERAGE: %s"
			self.SubjectsHeader = "\nSubjects:"
			self.SubjectSelDisplay = "ID: %s, subject: %s, professors: %s"
			self.GradeDate = "Date"
			self.GradeSubject = "Description"
			self.GradeNumber = "Grade"
			self.AverageGrade = "\nAVERAGE GRADE (calculated locally): %s (%s)"
			self.ConcludedGrade = "CONCLUDED GRADE (professor's decision): %s"
			self.NoGradesForSubject = "No grades for this subject"
			self.TestsHeader = "\nTests:\n"
			self.TestSchoolSubject = "Subject"
			self.TestSubject = "Test subject"
			self.TestDate = "Date"
			self.NoProfessorsForSubject = "No professor"
			self.CurrentCompleteAverage = "Current complete average: %s"
			self.CurrentCompleteAverageIncomplete = " (not all grades concluded!)"
			self.WrongCredentials = "Incorrect username or password. Please try again."

			self.RepTextHeader = "Class: %s (%s)\nSchool: %s, %s\nClassmaster: %s\n\nAVG_GRADE_PLACEHOLDER\n\n"
		elif lang == "hr":
			self.Help = "-lang en/hr/de\t\tForsiraj jezik (trenutno podržani: en, hr, de; zadan: hr)\n-debug\t\t\tOmogući debug log u EDAP libraryu\n-alltests\t\tPrikaži sve testove umjesto samo preostale\n-loglevel 0/1/2/3\tPostavi razinu zapisivanja (verbose/info/warning/error)\n-noanonrep\t\tNe šalji anonimne izvještaje korištenja\n-fullavg\t\tPrikaži samo prosjek svih predmeta\n-nohidepriv\t\tNe skrivaj privatne informacije u logovima\n-report\t\t\tZapiši izvještaj o ocjenama u \"report.txt\"\n"
			self.CredentialPrompt = "Molimo unesite Vaše podatke za prijavu.\nUPOZORENJE: Vaši podaci se šalju samo na \"ocjene.skole.hr\"\ni ostaju u radnoj memoriji samo tijekom prijave.\n"
			self.UsernamePrompt = "Korisničko ime: "
			self.PasswordPrompt = "Lozinka: "
			self.ClassSelDisplay = "ID %s\n  Razred: %s\n  Godina: %s\n  Škola: %s\n  Grad: %s\n  Razrednik: %s"
			self.SelectionTemplate = "\nOdabir (od 0 do %s): "
			self.ConcludedGradeMinified = "ZAKLJUČENO"
			self.AverageGradeMinified = "PROSJEK: %s"
			self.SubjectsHeader = "\nPredmeti:"
			self.SubjectSelDisplay = "ID: %s, predmet: %s, profesor: %s"
			self.GradeDate = "Datum"
			self.GradeSubject = "Opis"
			self.GradeNumber = "Ocjena"
			self.AverageGrade = "\nPROSJEČNA OCJENA (lokalno izračunato): %s (%s)"
			self.ConcludedGrade = "ZAKLJUČNA OCJENA (odluka profesora): %s"
			self.NoGradesForSubject = "Nema ocjena za ovaj predmet"
			self.TestsHeader = "\nIspiti:\n"
			self.TestSchoolSubject = "Predmet"
			self.TestSubject = "Predmet testa"
			self.TestDate = "Datum"
			self.NoProfessorsForSubject = "Nema profesora"
			self.CurrentCompleteAverage = "Trenutni opći prosjek: %s"
			self.CurrentCompleteAverageIncomplete = " (nisu sve ocjene zaključene!)"
			self.WrongCredentials = "Netočno korisničko ime ili lozinka. Molimo pokušajte ponovno."

			self.RepTextHeader = "Razred: %s (%s)\nŠkola: %s, %s\nRazrednik: %s\n\nAVG_GRADE_PLACEHOLDER\n\n"
		elif lang == "de":
			#print("[!!] Language %s/German is marked as being poorly or incompletely translated. You might experience difficulty understanding.")

			self.Help = "-lang en/hr/de\t\tSprache erzwingen (derzeit unterstützt: en, hr, de; Standard: hr)\n-debug\t\t\tDebug in EDAP-Modul aktivieren\n-alltests\t\tZeige alle Prüfungen anstatt nur von heute\n-loglevel 0/1/2/3\tLog-Level einstellen (verbose/info/warning/error)\n-noanonrep\t\tKeine anonyme Nutzungsdaten senden\n-fullavg\t\tNur durchschnitt aller Schulfächer anzeigen\n-nohidepriv\t\tPrivate Informationen in Protokollen (Logs) nicht verstecken\n-report\t\t\tBewertungsbericht in \"report.txt\" speichern\n"
			self.CredentialPrompt = "Bitte geben Sie Ihre Zugangsdaten ein.\nHAFTUNGSAUSSCHLUSS: Ihre Zugangsdaten werden nur an \"ocjene.skole.hr\" gesendet,\nund wird nur während der Anmeldung im RAM gehalten.\n"
			self.UsernamePrompt = "Nutzername: "
			self.PasswordPrompt = "Kennwort: "
			self.ClassSelDisplay = "ID %s\n  Schulklasse: %s\n  Jahre: %s\n  Schule: %s\n  Stadt: %s\n  Klassenmeister: %s"
			self.SelectionTemplate = "\nAuswahl (von 0 bis %s): "
			self.ConcludedGradeMinified = "ABSCHLUSSNOTE"
			self.AverageGradeMinified = "NOTENDURCHSCHNITT: %s"
			self.SubjectsHeader = "\nSchulfächer:"
			self.SubjectSelDisplay = "ID: %s, Schulfach: %s, Professoren: %s"
			self.GradeDate = "Datum"
			self.GradeSubject = "Notebeschreibung"
			self.GradeNumber = "Note"
			self.AverageGrade = "\nNOTENDURCHSCHNITT (lokal berechnet): %s (%s)"
			self.ConcludedGrade = "ABSCHLUSSNOTE (Entscheidung des Professors): %s"
			self.NoGradesForSubject = "Keine Noten für dieses Fach"
			self.TestsHeader = "\nPrüfungen:\n"
			self.TestSchoolSubject = "Schulfach"
			self.TestSubject = "Thema"
			self.TestDate = "Datum"
			self.NoProfessorsForSubject = "Keine Professoren"
			self.CurrentCompleteAverage = "Aktueller vollständiger Notendurchschnitt: %s"
			self.CurrentCompleteAverageIncomplete = " (nicht alle Noten abgeschlossen!)"
			self.WrongCredentials = "Falsches Nutzername oder Kennwort. Bitte versuchen Sie es noch einmal."

			self.RepTextHeader = "Klasse: %s (%s)\nSchule: %s, %s\nKlassenmeister: %s\n\nAVG_GRADE_PLACEHOLDER\n\n"
		else:
			print("[!!!] UNSUPPORTED LANGUAGE \"%s\"! No strings initialized; expect a crash to follow." % lang)